### ISSUE TITLE
Tiny bug in filter dump

### ISSUE THREAD

**Issue by orzdk** [TheKikGen/USBMidiKliK4x4#11]
**1** 
Filter dumps cable filters when serial filters are requested (mask 0x0F020100). Line 599 in the .ino should probably be

`    if (src) {`

**2**
Dump engine is not able to report cable/serial targets >7 due to inadequate var size. Changing line 539 to 

`uint16_t msk; `

seems to work. 

BR !

**Comment by TheKikGen** [comment]
Yes ! You are probably right.  This sysex dump module was not extensively tested yet....
Maybe you could push a PR ?

**Comment by orzdk** [comment]
I will try ! : ) Never made one before

**Comment by orzdk** [comment]
Done. Closing.
