### ISSUE TITLE
Need help to create midi on stm32

### ISSUE THREAD

**Issue by 4dvn** [TheKikGen/USBMidiKliK4x4#16]
I wanna to tranform midi on arduino code to stm32 with 16 buttons but i can't find how to make it can you help me the code of 16 buttons on stm32f103c8t6 with this library?

**Comment by TheKikGen** [comment]
Better to ask to the Arduino forum I think, or give more details about what you want to do !

**Comment by TheKikGen** [comment]
OK. I checked your Github : are you talking of the "Midi_Fighter_Classic" project ?  You want to port it to STM32 ?  Totally doable.  You have to start with https://github.com/rogerclarkmelbourne/Arduino_STM32
