### ISSUE TITLE
Bus related unit crash on sysex route reset

### ISSUE THREAD

**Issue by orzdk** [TheKikGen/USBMidiKliK4x4#17]
Hey, i will collect findings in issues here.

Summary: Setting or resetting routings by sysex crashes program loop

Symptoms: Blinking unresponsive unit, hangs midiox upon exit. When physical reset button pressed, midiox exists, and unit works again. Important: The changes that was requested by the sysex that crashed the unit, has actually correctly taken place.

The sysex processing comes back fine from the SysExInternalFnVector call which explains why it saves correctly, but fails when subsequently trying to sync the bus in [mod_i2cbus.h\I2C_SlavesRoutingSyncFromMaster()]

`483: I2C_SendCommand(0,   B_CMD_START_SYNC);`

Which is called from [mod_intsysex.h\SysExInternal_Process()]

`192: if ( SysExInternalFnVector[i].needBusSyncIfSucceed && !(B_IS_SLAVE) ) I2C_SlavesRoutingSyncFromMaster();`

I'm on a 3x3, verified bus mode is disabled and device id = 4. As it's not slave but not on the bus either, I2C sync should probably not start, so I made a hack to continue UI development, but it's probably not the correct solution.

`192: if ( SysExInternalFnVector[i].needBusSyncIfSucceed && !(B_IS_SLAVE) && EE_Prm.I2C_BusModeState == B_ENABLED ) I2C_SlavesRoutingSyncFromMaster();`

BR : )

**Comment by TheKikGen** [comment]
Bug solved .  You found the issue.
In a specific case, the master tried to synchronize slaves while the bus was disabled.
This internal sysex process was entirely reviewed with binary flags to sync, save, reboot, ack.
