### ISSUE TITLE
Removing last intelliroute for specific target not possible, only entire jack

### ISSUE THREAD

**Issue by orzdk** [TheKikGen/USBMidiKliK4x4#18]
Removing the last intelliroute on a jack **for a certain target**, will exit from SysExInternal_fnIThruSettings() with SX_ERROR_BAD_MSG_SIZE because msglen 4 is currently not supported. This means the only way to clear an intellithru jack target is to clear the jack completely, which will remove both physical and virtual jacks, and we maybe only wanted to remove one of them, for example: 

F0 77 78 0E 03 00 01 F7 (clear (last) jack ithru on jack0)
or
F0 77 78 0E 03 00 02 F7 (clear (last) virtual ithru on jack0)

Currently we can only
F0 77 78 0E 03 00 F7 (clear all ithrus on jack0)

Made a temporary fix in mod_intsysex.h that seemed to fix it,, by commenting out this line

if (msgLen < 5 ) return SX_ERROR_BAD_MSG_SIZE;

and then just set *msk = 0 if len =4.

But I am not sure at all if its the best solution, was just to continue testing. 
BR : )

**Comment by TheKikGen** [comment]
Right. That is missing for more flexibility. Request accepted.  Will be in the next push.
