### ISSUE TITLE
Loopback question

### ISSUE THREAD

**Issue by orzdk** [TheKikGen/USBMidiKliK4x4#24]
I understand that if a LOOPBCK pipe is used, no more pipes in the slot is run (illustrated by the red dashed object), but how about the "original" route, will that still be fullfilled? Consider this example, a channel voice filtered loopback to virtual0in has been added to jack0in. 

Question is, will channel voice reach virtual0in and the **unfiltered** message still reach cable0out, or will only channel voice reach virtual0in ?

Thanks for clarification : )
BR 

![ex1](https://user-images.githubusercontent.com/5564718/83867128-3ac97380-a729-11ea-831e-ee9f11c96de5.png)

**Comment by TheKikGen** [comment]
LoopBck copies the incoming packet but will not drop the original packet. So msg will reach cableOut.

**Comment by orzdk** [comment]
Thanks ! : )
