### ISSUE TITLE
Problem in version 2.5

### ISSUE THREAD

**Issue by MSMicro-ru** [TheKikGen/USBMidiKliK4x4#32]
Good work!
In version 2.5 (testing on blackpill F103c8, 64K firmware umk4x4.stm32f103c8-64k-o2.bin) :
after sending command: Reboot in configuration mode (F0 77 77 78 06 08 F7) - 
device is reboot in update mode!
USB\VID_1209&PID_BEBA\
After reflashing - device onсe enter to config mode (COM Port is on),
and after - no entering to configuration mode.

**Comment by TheKikGen** [comment]
At the first boot, configuration mode is enabled automatically.
If you save the configuration, the next time, the board will boot as a midi interface.
In  configuraiton mode, try to reset all parameters, save and exit.
Sometimes behaviour can differ between BluePill boards (not the same resistors, STM32 clones, etc...)

**Comment by MSMicro-ru** [comment]
Yes,, all works, as you say, but
after sending command: Reboot in configuration mode (F0 77 77 78 06 08 F7) -
device is reboot in UPDATE mode!
