### ISSUE TITLE
Controlador midi personalizado

### ISSUE THREAD

**Issue by Veroledez** [TheKikGen/USBMidiKliK4x4#33]
Hola, gracias por compartir tu libreria.

Quiero hacer mi propio controlador y que en el pc aparezcan dos puertos mido usb, pero solo usando un stm32, y me preguntaba si esta libreria soporta  botones y potenciometros, o solo rutea el midi a usb.

Agradezco tu orientacion.

**Comment by TheKikGen** [comment]
Hello,  

First please post in english for a better understanding of the project community (Google Translation...).
The project is STM32 based, so you can add potentiometers, or buttons as usual.  
I implemented it in the Midiplus Smartpad (a Launchpad chinese clone) with 64 pads, 8 pots, 24 buttons...
Check the Kikpad projet here : https://github.com/TheKikGen/kikpad
