### ISSUE TITLE
Building Arduino Code!

### ISSUE THREAD

**Issue by LenarOsx** [TheKikGen/USBMidiKliK4x4#38]
Hey thanks for the code, im trying to build the arduino code, but the file midiXparser.h is missing, I trying to mod the code cause I need to get the multi midi usb cable(ports ) code for another project. Please help

**Comment by TheKikGen** [comment]
Check other project on my Github.
MidiXparser is here :  https://github.com/TheKikGen/midiXparser

**Comment by TheKikGen** [comment]
And read that : https://github.com/TheKikGen/USBMidiKliK4x4/wiki/Build-UsbMidiKlik4x4-from-sources
