### ISSUE TITLE
CHANMAP does not work in channel map mode because of a code bug

### ISSUE THREAD

**Issue by iflyhigh** [TheKikGen/USBMidiKliK4x4#43]
The code below is missing `else` statement after the second `if`. Currently it causes any pipe with CHANMAP set to `channel map  (i.e. ==0) ` mode just to drop the MIDI message because the last `if` fires unconditionally, returns `false` thus the whole function returns `false`. Observed live in my setup.

``` 
mod_miditransfn_pipes.h
...
  // Map channel to channel
  if (pipe->par1 == 0 ) {
...
  }
  else
  // Map channel to port (of the same port type)
  if (pipe->par1 == 1 ) {
...
  }
  // channel offset
  if (pipe->par1 == 2 ) {
...
  }
  else return false; // Error
```

**Comment by TheKikGen** [comment]
Hi. Thanks for that. You are right. Else is missing here.  could you push a change request, so you will appear in contributors list :-) !

**Comment by TheKikGen** [comment]
Forget. I did it...
