### ISSUE TITLE
Small change to manual, switch to config mode is missing a byte in the example

### ISSUE THREAD

**Issue by fairuse** [TheKikGen/USBMidiKliK4x4#48]
Section 4.3.1 of the manual at https://github.com/TheKikGen/USBMidiKliK4x4/wiki/UMK4x4-V2.5-User-Manual reads:

    Switch the board in configuration mode by sending the sysex "F0 77 77 78 08 F7" The board will disconnect and connect again in serial mode. You should see the led blinking very quickly.

But the actual sequence is "F0 77 77 78 **06** 08 F7". It is correct in the `readme.md`, but misses the 06 in the documentation.

**Comment by TheKikGen** [comment]
Thanks for pointing that !
