### ISSUE TITLE
Version 2.5.2 doesn't work in standalone mode from usb charger

### ISSUE THREAD

**Issue by DanielHabart** [TheKikGen/USBMidiKliK4x4#53]
Version 2.5.2 doesn't work in standalone mode from usb charger on a hacked Midiface4x4. Gets stuck on all LEDs on. No such problem when connected to the computer but without sending any midi info and hence turning into standalone mode by itself.

**Comment by TheKikGen** [comment]
Hi,  did you test any previous version ?  I have the same behaviour with my Midiface also.

**Comment by DanielHabart** [comment]
Thanks for getting back to me. I then tried a previous version and that worked without problems. I think it was the version without the new bootloader (?).Maybe it was just an upload issue, although I assume I must have tried uploading multiple times.On 23. 12. 2024, at 13:52, TheKikGen ***@***.***> wrote:﻿
Hi,  did you test any previous version ?  I have the same behaviour with my Midiface also.

**Comment by TheKikGen** [comment]
Bug corrected in the 2.53 release, published today.
https://github.com/TheKikGen/USBMidiKliK4x4/releases/tag/v2.5.3
