### ISSUE TITLE
Just a little help ?

### ISSUE THREAD

**Issue by AurelGTS** [TheKikGen/USBMidiKliK4x4#6]
Hello,
This issue is just to start conversation, this is not an issue on your project ...
I m  working on a midi device with a blue pill. I m working with STM32duino USBComposite library.
Your library seems close to this USBComposite library. So I would appreciate your help if possible :) I think it could be quickly fixed.
I have a problem : I can receive data but I can't transmit... If you have a little bit time to help me, I ll be thankful. I think its perhaps : 
- usb descriptors which are not correct.
- bootloader issue but I m not sure...

Thanks in advance.
Regards
Aurélien

**Comment by TheKikGen** [comment]
Hello Aurelien,
Have a look in the descriptor here . The STM32DUINO bootloader is not the problem.  Know that the USB composite is sometimes unstable....Start with a basic midi out.

**Comment by AurelGTS** [comment]
Hello, 


Thanks for your feedback. Midiout.ino example just work fine. 
I copied all your code and I ve same behavior : no data transmitted. 

I really don't understand. 


regards, 


Aurélien 

----- Mail original -----

De: "TheKikGen" <notifications@github.com> 
À: "TheKikGen/USBMidiKliK4x4" <USBMidiKliK4x4@noreply.github.com> 
Cc: "AurelGTS" <benoit.aurelien@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 2 Octobre 2019 22:45:49 
Objet: Re: [TheKikGen/USBMidiKliK4x4] Just a little help ? (#6) 


Hello Aurelien, 
Have a look in the descriptor here . The STM32DUINO bootloader is not the problem. Know that the USB composite is sometimes unstable....Start with a basic midi out.

**Comment by TheKikGen** [comment]
Aurélien, please stop to post here as it is not a general purpose forum.  Post to the Arduino forum, open a new topic with your issue.  Thanks !
